// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
)

type (
	IDown interface {
		Create(ctx context.Context, issueNo uint) (filename string, err error)
	}
)

var (
	localDown IDown
)

func Down() IDown {
	if localDown == nil {
		panic("implement not found for interface IDown, forgot register?")
	}
	return localDown
}

func RegisterDown(i IDown) {
	localDown = i
}
